### ISSUE TITLE
Question regarding your solution of chapter 1 exercise 16.

### ISSUE THREAD

**Issue by ksatwar** [hiverkiya/Dennis-Ritchie-C-Solutions#3]
Exercise 1-16. Revise the main routine of the longest-line program so it will correctly print the length of arbitrary long input lines, and as much as possible of the text.

in your solution to the aforementioned problem, you seem to not have solved it at all. Also the main block does not seem to have a return value. Am I wrong in my understanding? 

Thank you in advance.

**Comment by hiverkiya** [comment]
Hello @ksatwar, I apologize for the late reply. A lot of time has passed since I've been in touch with C, and unfortunately, I don't have the book with me. I'd request you verify the mentioned correction from your end and open a PR regarding that. I'd be happy to merge any further rectifications and add them under the hacktoberfest label.
